@startuml
title Database Diagram - Bounded Context: Vital Signs Capture
hide circle
skinparam linetype ortho

entity "episodes" as episodes {
  * id : VARCHAR(20) <<PK>>
  --
  * vitals_json : NVARCHAR(MAX)
  * confirmed : BIT
  vitals_confirmed_at : DATETIME2
}
entity "devices" as devices {
  * id : INT <<PK>>
  --
  * type : VARCHAR(8)
  * model : VARCHAR(60)
  * online : BIT
  last_use : VARCHAR(5)
  linked_episode : VARCHAR(20) <<FK>>
}
episodes |o--o{ devices
@enduml
