@startuml
title Database Diagram - Bounded Context: Patient Registration
hide circle
skinparam linetype ortho

entity "patients" as patients {
  * id : INT <<PK>>
  --
  * doc_type : VARCHAR(8)
  * sin_dni : BIT
  dni : VARCHAR(12)
  * names : VARCHAR(80)
  * surnames : VARCHAR(80)
  * birth : DATE
  * sex : VARCHAR(1)
  phone : VARCHAR(20)
  address : VARCHAR(200)
}
entity "sexes" as sexes {
  * id : INT <<PK>>
  --
  * name : VARCHAR(15)
}
entity "episodes" as episodes {
  * id : VARCHAR(20) <<PK>>
  --
  * key : VARCHAR(12)
  * patient_id : INT <<FK>>
  * arrival : DATETIME2
  * confirmed : BIT
  vitals_confirmed_at : DATETIME2
  * referred : BIT
  * vitals_json : NVARCHAR(MAX)
}
patients }o--o| sexes
episodes }o--|| patients
@enduml
